import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="flex flex-col h-screen">
          <Header />
          <div className="flex flex-1">
            <div className="bg-white">
              {/* Sidebar content goes here */}
            </div>
            <div className="flex-1 bg-gray-100 overflow-y-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
              <div className="h-full">{children}</div>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}